version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: kites-mq
      RABBITMQ_DEFAULT_PASS: kites262
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: kites-db-root
      MONGO_INITDB_ROOT_PASSWORD: kites262
      MONGO_INITDB_DATABASE: hic
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
